#general - all required
shop_name: Recon-Bot Shop
shop_domain: shop.reconbot.xyz
shop_email_support: help@reconbot.xyz
shop_email_noreply: noreply@reconbot.xyz

#email - all required, for email delivery in production
SMTP_host: mbox.freehostia.com
SMTP_port: 995
SMTP_username: help@reconbot.xyz
SMTP_password: s1n#Rila

#payments - all required, for processing payments
stripe_api_key: sk_test_UIOrNRqCuNxR05ZSdFYZIvRV00qPxcb7KI
stripe_publishable_key: pk_test_xehj0ck2Dw4vxvPmUbh7W3Bx009rUsU7nU

#file storage - all required, for storing files securely
AWS_REGION: US East (N. Virginia)
AWS_BUCKET: zipsell-xdgt
AWS_ACCESS_KEY_ID: 4cee60c3ffbdc870a8baebae7182184410af0f725d2a98fbfa74cf1d6eaada59
AWS_SECRET_ACCESS_KEY: zipsell-accesssss

#file management - all required
file_expiry_hours: "24"
file_max_downloads: "10"

#cdn host - optional, for faster static asset serving in production
cdn_host_assets: 
cdn_host_s3_bucket: 

#analytics - optional, in the format UA-XXXXXXXX-XX
google_analytics_id:

#
# production:
#   stripe_api_key: 
#   stripe_publishable_key: 
